include: ['projects']
markdown : kramdown
kramdown:
  input: GFM
email: "roy.e.mosby@gmail.com"
facebook: "https://www.facebook.com/roy.e.mosby"
github: "https://github.com/egomadking"
phone: "1-234-804-4350"
linkedin: "https://www.linkedin.com/in/roy-mosby/"
twitter: "https://twitter.com/royemosby"